#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if ! iptables -L > /dev/null 2>&1; then
  error "iptables is not functional. Ensure your container config adds --cap-add=NET_RAW" 
fi

iptables -F
iptables -X

info "Starting firewall"
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP

info "Enabling connection to secure interfaces"
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

iptables -A INPUT -i lo -j ACCEPT
iptables -A FORWARD -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

iptables -A INPUT -i wg+ -j ACCEPT
#iptables -A FORWARD -i wg+ -j ACCEPT
iptables -A OUTPUT -o wg+ -j ACCEPT

ifaces=($(ip link | awk -F': ' '$0 !~ "lo|wg|tun|tap|^[^0-9]"{print $2;getline}' | cut -d@ -f1))
for iface in "${ifaces[@]}"; do
  inet="$(ip -o addr show dev "${iface}" | awk '$3 == "inet" {print $4}')"
  if [[ -z "$inet" ]]; then
    warn "Skipping connection to ${iface} ${inet}"
    continue
  fi
  info "Enabling connection to ${iface} ${inet}"
  iptables -A INPUT -i "$iface" -s "${inet}" -j ACCEPT
  iptables -A OUTPUT -o "$iface" -d "${inet}" -j ACCEPT
  iptables -A FORWARD -i "$iface" -d "${inet}" -j ACCEPT
  iptables -A FORWARD -i "$iface" -s "${inet}" -j ACCEPT
  iptables -A OUTPUT -o "$iface" -p udp -m udp --dport 51820 -j ACCEPT
done

